name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.8
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'BC' # an FFI blog post requirement
          version: '8.2'
          packages: 'gregor,frog,honu'
      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      - name: Build website
        run: |
          sudo apt-get install -y python-pygments 
          sudo make all
          sudo git config --global user.name "github-actions[bot]"
          sudo git config --global user.email "nuprl+github-actions[bot]@users.noreply.github.com"
          sudo git add -A -f
          sudo git checkout -b "deploy"
          sudo git commit --allow-empty -m "** deploy nuprl/website@$GITHUB_SHA"
          sudo git push origin deploy -f
